### ISSUE TITLE
[Epic] Migrate Set Up Commands to Swift Command 

### ISSUE THREAD

**Issue by blyscuit** [nimblehq/ios-templates#503]
## Why

Migrate our set up commands to Swift command to ease maintenance for newcomers.

## Who Benefits?

Template Developers
```[tasklist]
### Tasks
- [ ] https://github.com/nimblehq/ios-templates/issues/490
- [ ] https://github.com/nimblehq/ios-templates/issues/494
- [ ] https://github.com/nimblehq/ios-templates/issues/491
- [ ] https://github.com/nimblehq/ios-templates/issues/492
- [ ] https://github.com/nimblehq/ios-templates/issues/495
```
